language: php

php:
  - 5.6
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: PREFER_LOWEST=1

    - php: 7.4
      env: CHECKS=1 DEFAULT=0

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction; fi

  - if [[ $CHECKS == 1 ]]; then composer require --dev phpstan/phpstan:^0.12; fi

script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.4 ]]; then vendor/bin/phpunit; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.4 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

  - if [[ $CHECKS = 1 ]]; then composer cs-check; fi
  - if [[ $CHECKS = 1 ]]; then vendor/bin/phpstan analyse src/; fi

after_success:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.4 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
